# data
data:
  eval_data: '../moshi_ft_runs/training_data/elon_convo/pods100/eval.jsonl,../moshi_ft_runs/training_data/elon_convo/everyday/eval.jsonl'
  shuffle: true
  train_data: '../moshi_ft_runs/training_data/elon_convo/pods100/train.jsonl,../moshi_ft_runs/training_data/elon_convo/everyday/train.jsonl'
  with_replacement: true

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false # Activate lora.enable if partial finetuning
lora:
  enable: true # Set to False if full_finetuning is True
  rank: 16
  scaling: 32.
  ft_embed: false # Optional, set to True if you want to finetune the embedding layer

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim
duration_sec: 30
batch_size: 8 
max_steps: 100
gradient_checkpointing: true
optim:
  lr: 1e-5
  weight_decay: 0.1
  pct_start: 0.05
  muon_lr: 1e-4

use_muon: true

# other
seed: 0
log_freq: 1
eval_freq: 50 
do_eval: true
do_ckpt: false
ckpt_freq: 100

save_adapters: true # Must be False if full_finetuning is True

run_dir: "../moshi_ft_runs/runs/elon_pods_muon_local"  # Fill
overwrite_run_dir: true

description: "adamw+muon on pods100+everyday local, 1e-5 lr 1e-4 muon, lora_alpha2->32 rank16"


# This part is optional and can be kept commented out
# wandb:
#   project: "" # your wandb project name
#   run_name: "" # your wandb run name
#   key: "" # your wandb api key
#   offline: False
