# data
data:
  eval_data: '../moshi_ft_runs/training_data/elon_convo/pods100/eval.jsonl,../moshi_ft_runs/training_data/elon_convo/everyday/eval.jsonl'
  shuffle: true
  train_data: '../moshi_ft_runs/training_data/elon_convo/pods100/train.jsonl,../moshi_ft_runs/training_data/elon_convo/everyday/train.jsonl'
  with_replacement: true

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false # Activate lora.enable if partial finetuning
lora:
  enable: true # Set to False if full_finetuning is True
  rank: 128 
  scaling: 2.
  ft_embed: false # Optional, set to True if you want to finetune the embedding layer

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim
duration_sec: 30
batch_size: 16 
max_steps: 10000
gradient_checkpointing: true
optim:
  lr: 5e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 10
eval_freq: 200 
do_eval: true
do_ckpt: true
ckpt_freq: 500

save_adapters: true # Must be False if full_finetuning is True

overwrite_run_dir: true

run_dir: "../moshi_ft_runs/runs/elon_pods100"  # Fill
description: "pods100+everyday"

# This part is optional and can be kept commented out
# wandb:
#   project: "" # your wandb project name
#   run_name: "" # your wandb run name
#   key: "" # your wandb api key
#   offline: False
